#!/usr/bin/env python3
"""Generate ``rust/bsk_messages/src/lib.rs`` from the vendored BSK C headers.

The output is gitignored (generated code doesn't belong in the source tree),
so this script must be run at least once in any ``bsk_sdk`` checkout before
a plugin crate can build against ``bsk-messages`` (plugin ``Cargo.toml``
files reference it by a relative path into this checkout, not a published
crate). Re-run it whenever ``sync_headers.py`` updates the vendored headers
(i.e. after every Basilisk release).

Requirements
------------
* ``bindgen`` CLI must be on ``$PATH``.  Install once with::

      cargo install bindgen-cli

* ``libclang`` must be available (``libclang-dev`` on Debian/Ubuntu).

Usage
-----
::

    python3 tools/gen_rust_messages.py [--bsk-include DIR] [--out FILE]

``--bsk-include`` defaults to the include root inside the installed ``bsk_sdk``
Python package (``bsk_sdk.include_dir()``).
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

FILE_HEADER = """\
// This file is AUTO-GENERATED by tools/gen_rust_messages.py.
// DO NOT EDIT BY HAND.
//
// Re-run `python3 tools/gen_rust_messages.py` after every `sync_headers.py`
// update to keep these bindings in sync with the vendored BSK headers.
//
// Crate: bsk-messages
// Source: cMsgCInterface headers vendored in bsk_sdk

#![allow(non_snake_case, non_camel_case_types, non_upper_case_globals, dead_code, clippy::all)]

"""

# Hand-written Rust source appended after the bindgen output: the runtime
# mirror struct, Msg/MsgReader/MsgWriter/BskModule, and logging support.
# `bsk_module!()` itself is *not* here — see `bsk_build`'s crate docs for why.
RUNTIME_SUPPORT_CODE = '''\
/// Rust-side mirror of the C ``BskRustModuleRuntime`` struct declared in
/// ``bsk_rust_module.h``. Refreshed from the config struct's own ``runtime``
/// field before every ``SelfInit``/``Reset``/``Update`` call, so a module
/// reads framework state (``moduleID``, ``ModelTag``, ``CallCounts``,
/// ``RNGSeed``) the same way it reads any other config field.
///
/// Deliberately not `Copy`/`Clone`: `model_tag()` borrows from `&self`, and
/// its pointee is only valid for the current lifecycle call, so the compiler
/// rejects any attempt to hold onto the string past that call. Duplicating
/// this struct by value (e.g. into a field of your own) would let that
/// pointer be read again later, once it's dangling — see `model_tag()`.
#[repr(C)]
#[derive(Debug)]
pub struct BskModuleRuntime {
    module_id: i64,
    model_tag: *const core::ffi::c_char,
    call_counts: u64,
    rng_seed: u32,
}

impl BskModuleRuntime {
    /// Framework-assigned message-writer identifier (``SysModel::moduleID``).
    pub const fn module_id(&self) -> i64 { self.module_id }
    /// Step counter (``SysModel::CallCounts``).
    pub const fn call_counts(&self) -> u64 { self.call_counts }
    /// Random seed (``SysModel::RNGSeed``).
    pub const fn rng_seed(&self) -> u32 { self.rng_seed }
    /// Python-assigned module name (``SysModel::ModelTag``).
    ///
    /// Borrowed from `&self`, which in turn is only ever handed to module
    /// code for the duration of the current lifecycle call — the borrow
    /// checker rejects any attempt to retain the returned `&str` past it.
    pub fn model_tag(&self) -> &str {
        if self.model_tag.is_null() {
            return "";
        }
        unsafe { core::ffi::CStr::from_ptr(self.model_tag) }
            .to_str()
            .unwrap_or("")
    }
}

impl BskModuleRuntime {
    /// An all-zero runtime (module ID 0, empty tag, no calls yet) for
    /// constructing a config struct in a `#[cfg(test)]` unit test, without a
    /// live simulation to supply a real one. Not named/spelled `default()`
    /// (no `Default` impl) so `mem::take`/`mem::replace` can't be used to
    /// pull a live runtime out of a config struct by value.
    pub const fn for_testing() -> Self {
        Self { module_id: 0, model_tag: core::ptr::null(), call_counts: 0, rng_seed: 0 }
    }
}

/// A Basilisk message value, e.g. ``AttGuidMsg`` or ``CmdTorqueBodyMsg``.
///
/// Implemented once per Basilisk message type further below (auto-generated
/// from the vendored headers). Module authors never call these methods
/// directly — read/write messages through [`MsgReader`]/[`MsgWriter`] instead.
pub trait Msg: Sized + Copy {
    /// The C-interface port type this message is read from / written to.
    type Port: Default;
    #[doc(hidden)]
    fn __is_linked(port: &mut Self::Port) -> bool;
    #[doc(hidden)]
    fn __read(port: &mut Self::Port) -> Self;
    #[doc(hidden)]
    fn __init(port: &mut Self::Port);
    #[doc(hidden)]
    fn __write(data: &Self, port: &mut Self::Port, module_id: i64, current_sim_nanos: u64);
}

/// An input message port — reads a [`Msg`] written by another module.
///
/// Use as a config struct field type, e.g. ``pub attGuidInMsg:
/// MsgReader<AttGuidMsg>``. Has the same memory layout as the message's
/// C-interface port struct, so the generated C header sees a plain
/// ``AttGuidMsg_C`` field.
#[repr(transparent)]
pub struct MsgReader<T: Msg>(T::Port);

impl<T: Msg> Default for MsgReader<T> {
    fn default() -> Self { Self(T::Port::default()) }
}

impl<T: Msg> MsgReader<T> {
    /// Whether another module has subscribed this port to a source message.
    pub fn is_linked(&mut self) -> bool { T::__is_linked(&mut self.0) }
    /// Read the current message value.
    pub fn read(&mut self) -> T { T::__read(&mut self.0) }
}

/// An output message port — writes a [`Msg`] for other modules to read.
///
/// Use as a config struct field type, e.g. ``pub cmdTorqueOutMsg:
/// MsgWriter<CmdTorqueBodyMsg>``.
#[repr(transparent)]
pub struct MsgWriter<T: Msg>(T::Port);

impl<T: Msg> Default for MsgWriter<T> {
    fn default() -> Self { Self(T::Port::default()) }
}

impl<T: Msg> MsgWriter<T> {
    /// Claim ownership of this output message. Called automatically from the
    /// generated ``SelfInit`` — module code does not need to call this.
    pub fn init(&mut self) { T::__init(&mut self.0) }
    /// Write a new message value.
    pub fn write(&mut self, data: &T, module_id: i64, current_sim_nanos: u64) {
        T::__write(data, &mut self.0, module_id, current_sim_nanos)
    }
}

/// Strongly typed Rust lifecycle interface mirrored by the Basilisk C ABI shim.
///
/// A module's config struct implements this trait directly — no Rust code
/// depends on the C++ ``SysModel`` class. Runtime data (module ID,
/// ``ModelTag``, etc.) is available through the config's own
/// ``runtime: BskModuleRuntime`` field, read like any other config field.
/// ``current_sim_nanos`` is passed directly, since ``SysModel`` doesn't store it.
pub trait BskModule {
    type Inputs;
    type Outputs;

    fn self_init(&mut self) {}
    fn reset(&mut self, _current_sim_nanos: u64) {}
    fn update(&mut self, inputs: Self::Inputs, current_sim_nanos: u64) -> Self::Outputs;
}

// ---------------------------------------------------------------------------
// Logging — the Rust-side equivalent of a hand-written C module calling
// `_bskLog(configData->bskLogger, BSK_WARNING, info)` / `_bskError(...)`.
//
// Hand-declared here (not left to bindgen) for two reasons: bindgen also
// emits the raw, Itanium-mangled `BSKLogger::bskLog`/`BSKLogger::bskError`
// C++ methods once `BSKLogger` is allowlisted as a type, but those are
// variadic C++ methods — fragile to call across the FFI boundary and not
// meant for direct use. `_bskLog`/`_bskError`/`_BSKLogger` are the stable,
// non-variadic `extern "C"` wrappers Basilisk itself declares in
// `bskLogging.h` for exactly this purpose. They are declared
// `extern "C-unwind"`, not plain `extern "C"`: `_bskError` throws a C++
// `BasiliskError` exception, and per Rust's stabilized C-unwind ABI
// (https://github.com/rust-lang/rfcs/blob/master/text/2945-c-unwind-abi.md),
// letting an exception cross a plain `extern "C"` boundary is undefined
// behavior — only `"C-unwind"` guarantees it propagates cleanly instead of
// aborting the process.
extern "C-unwind" {
    fn _BSKLogger() -> *mut BSKLogger;
    fn _bskLog(logger: *mut BSKLogger, level: logLevel_t, info: *const ::core::ffi::c_char);
    fn _bskError(logger: *mut BSKLogger, info: *const ::core::ffi::c_char) -> !;
}

/// Basilisk's standard logging levels and error-raising, for a config
/// struct's ``bskLogger: *mut BSKLogger`` field — the same
/// ``_bskLog``/``_bskError`` entry points a hand-written Basilisk C module
/// calls directly (``_bskLog(configData->bskLogger, BSK_WARNING, info)``).
///
/// A null logger (module under test, or Python never set one) falls back
/// to a process-wide default logger, so these are always safe to call.
pub trait BskLoggerExt {
    /// Log `msg` at `level` (one of the four ``BSK_*`` constants).
    fn bsk_log(self, level: logLevel_t, msg: &str);
    /// [`BSK_DEBUG`] convenience wrapper.
    fn debug(self, msg: &str)
    where
        Self: Sized,
    {
        self.bsk_log(BSK_DEBUG, msg);
    }
    /// [`BSK_INFORMATION`] convenience wrapper.
    fn info(self, msg: &str)
    where
        Self: Sized,
    {
        self.bsk_log(BSK_INFORMATION, msg);
    }
    /// [`BSK_WARNING`] convenience wrapper.
    fn warning(self, msg: &str)
    where
        Self: Sized,
    {
        self.bsk_log(BSK_WARNING, msg);
    }
    /// Logs at [`BSK_ERROR`] and raises the standard fatal ``BasiliskError``
    /// (propagated to Python through the generated ``extern "C-unwind"``
    /// lifecycle entry points) — the Rust equivalent of a C module's
    /// ``_bskError(configData->bskLogger, info)``.
    fn bsk_error(self, msg: &str) -> !;
}

impl BskLoggerExt for *mut BSKLogger {
    fn bsk_log(self, level: logLevel_t, msg: &str) {
        unsafe {
            let logger = if self.is_null() { _BSKLogger() } else { self };
            if let Ok(c_msg) = ::std::ffi::CString::new(msg) {
                _bskLog(logger, level, c_msg.as_ptr());
            }
        }
    }

    fn bsk_error(self, msg: &str) -> ! {
        unsafe {
            let logger = if self.is_null() { _BSKLogger() } else { self };
            if let Ok(c_msg) = ::std::ffi::CString::new(msg) {
                _bskError(logger, c_msg.as_ptr());
            }
            _bskError(logger, c"BSK Rust module error (message contained a NUL byte)".as_ptr());
        }
    }
}
'''

WRAPPER_TEMPLATE = """\
/* Wrapper header: include every cMsgCInterface message header in one shot.
 * Generated by gen_rust_messages.py. */
#include <stdint.h>
#include <stddef.h>

/* BSKLogger and logLevel_t — not transitively included by the message
 * headers but needed by modules that hold a BSKLogger pointer. */
#include "Basilisk/architecture/utilities/bskLogging.h"

{includes}
"""


def find_bsk_include() -> Path:
    """Return the bsk_sdk include root, preferring the installed package."""
    try:
        import bsk_sdk  # type: ignore[import]
        inc = Path(bsk_sdk.include_dir())
        if inc.exists():
            return inc
    except Exception:
        pass
    # Fall back to the path relative to this script inside the repo.
    candidate = REPO_ROOT / "src" / "bsk_sdk" / "include"
    if candidate.exists():
        return candidate
    raise RuntimeError(
        "Cannot locate bsk_sdk include root. "
        "Either install bsk_sdk (`pip install -e .` in the bsk_sdk repo) "
        "or pass --bsk-include explicitly."
    )


def build_wrapper_header(cmsg_dir: Path) -> str:
    headers = sorted(cmsg_dir.glob("*_C.h"))
    # Use the full path so the wrapper header works regardless of working dir.
    includes = "\n".join(f'#include "{h}"' for h in headers)
    return WRAPPER_TEMPLATE.format(includes=includes)


def run_bindgen(
    wrapper_path: Path,
    include_dirs: list[Path],
    extra_clang_args: list[str],
) -> str:
    if not shutil.which("bindgen"):
        sys.exit(
            "ERROR: `bindgen` not found on $PATH.\n"
            "Install it with:  cargo install bindgen-cli"
        )

    # bindgen takes its own flags, then `--`, then raw clang flags.
    clang_args: list[str] = [f"-I{d}" for d in include_dirs] + extra_clang_args

    cmd = [
        "bindgen",
        str(wrapper_path),
        "--use-core",
        "--no-prepend-enum-name",
        "--merge-extern-blocks",
        "--with-derive-default",
        # Keep only the message-relevant surface: payloads, *_C structs,
        # MsgHeader, BSKLogger, and the C-interface functions.
        "--allowlist-type", r".*MsgPayload|.*Msg_C|MsgHeader|BSKLogger|logLevel_t",
        "--allowlist-function", r".*Msg_C_.*",
        # BSKLogger is a C++ class under __cplusplus; treat it as opaque.
        "--opaque-type", "BSKLogger",
        "--",   # everything after this is passed verbatim to clang
        *clang_args,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        sys.exit(
            f"ERROR: bindgen failed (exit {result.returncode}):\n{result.stderr}"
        )
    return result.stdout


def rename_payload_to_msg(text: str) -> str:
    """Rename bindgen's ``FooMsgPayload`` to ``FooMsg`` throughout.

    The Rust binding calls a message's data type ``Msg`` (read/written via
    ``MsgReader``/``MsgWriter``), not ``MsgPayload``. The underlying
    Basilisk C struct is still named ``FooMsgPayload``; this is a
    Rust-binding-only rename.
    """
    return re.sub(r"MsgPayload\b", "Msg", text)


def rename_port_data_field(text: str) -> str:
    """Rename the ``payload``/``payloadPointer`` fields bindgen generates for
    every ``FooMsg_C`` port struct to ``data``/``dataPointer``.

    These fields exist only so the Rust struct's layout matches Basilisk's C
    ``FooMsg_C`` (which does call the field ``payload`` — this is a
    Rust-binding-only rename, same as ``rename_payload_to_msg`` above). No
    generated Rust code reads either field by name (``MsgReader``/
    ``MsgWriter`` call the C read/write functions instead), so this only
    changes what a field name in the crate's source, not behavior.

    Scoped to the exact field-declaration/offset-assertion syntax bindgen
    emits, so it doesn't touch unrelated prose like a doc comment's "message
    payload".
    """
    text = re.sub(r"\bpayloadPointer\b(?=[:,)])", "dataPointer", text)
    text = re.sub(r"\bpayload\b(?=[:,)])", "data", text)
    text = text.replace('::payloadPointer"', '::dataPointer"')
    text = text.replace('::payload"', '::data"')
    return text


def find_message_types(text: str) -> list[str]:
    """Return every message base name (``AttGuidMsg`` from ``AttGuidMsg_C``)."""
    return sorted(set(re.findall(r"pub struct (\w+Msg)_C\b", text)))


def render_msg_trait_impls(message_types: list[str]) -> str:
    """One ``impl Msg for <Type>`` block per Basilisk message, wiring the
    renamed message type to its C-interface port struct and
    read/write/init/is_linked functions."""
    parts = ["// Auto-generated `Msg` trait impl for every Basilisk message type.\n"]
    for m in message_types:
        parts.append(
            f"impl Msg for {m} {{\n"
            f"    type Port = {m}_C;\n"
            f"    fn __is_linked(port: &mut {m}_C) -> bool {{ unsafe {{ {m}_C_isLinked(port) != 0 }} }}\n"
            f"    fn __read(port: &mut {m}_C) -> Self {{ unsafe {{ {m}_C_read(port) }} }}\n"
            f"    fn __init(port: &mut {m}_C) {{ unsafe {{ {m}_C_init(port) }} }}\n"
            f"    fn __write(data: &Self, port: &mut {m}_C, module_id: i64, current_sim_nanos: u64) {{\n"
            f"        unsafe {{ {m}_C_write(data as *const {m} as *mut {m}, port, module_id, current_sim_nanos) }}\n"
            f"    }}\n"
            f"}}"
        )
    return "\n".join(parts) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--bsk-include",
        metavar="DIR",
        help="bsk_sdk include root (parent of cMsgCInterface/ and Basilisk/)",
    )
    parser.add_argument(
        "--out",
        metavar="FILE",
        default=str(REPO_ROOT / "rust" / "bsk_messages" / "src" / "lib.rs"),
        help="Output path for the generated lib.rs "
             "(default: rust/bsk_messages/src/lib.rs)",
    )
    args = parser.parse_args()

    inc_root = Path(args.bsk_include).resolve() if args.bsk_include else find_bsk_include()
    cmsg_dir = inc_root / "cMsgCInterface"
    if not cmsg_dir.exists():
        sys.exit(f"ERROR: cMsgCInterface directory not found under {inc_root}")

    bsk_inc = inc_root / "Basilisk"

    print(f"Using include root: {inc_root}")
    print(f"  cMsgCInterface:   {cmsg_dir}  ({len(list(cmsg_dir.glob('*_C.h')))} message headers)")

    wrapper = build_wrapper_header(cmsg_dir)

    with tempfile.NamedTemporaryFile(suffix=".h", mode="w", delete=False) as f:
        f.write(wrapper)
        wrapper_path = Path(f.name)

    try:
        raw = run_bindgen(
            wrapper_path,
            # cMsgCInterface headers include "architecture/..." paths so we
            # need both the bare include root and the Basilisk sub-tree.
            # Some payload headers use <string>, so compile as C++.
            include_dirs=[inc_root, bsk_inc],
            extra_clang_args=["-std=c++17", "-x", "c++"],
        )
    finally:
        wrapper_path.unlink(missing_ok=True)

    raw = rename_payload_to_msg(raw)
    raw = rename_port_data_field(raw)
    message_types = find_message_types(raw)
    msg_impls = render_msg_trait_impls(message_types)
    print(f"  Msg trait impls:  {len(message_types)} message types")

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(FILE_HEADER + RUNTIME_SUPPORT_CODE + "\n" + raw + "\n" + msg_impls)
    print(f"Wrote {out_path}  ({out_path.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
