#!/usr/bin/env python3
#
#  ISC License
#
#  Copyright (c) 2026, Autonomous Vehicle Systems Lab, University of Colorado at Boulder
#
#  Permission to use, copy, modify, and/or distribute this software for any
#  purpose with or without fee is hereby granted, provided that the above
#  copyright notice and this permission notice appear in all copies.
#
"""Generate Rust FFI bindings for selected Basilisk C ABI utilities.

The generated bindings intentionally cover only C ABI headers.  C++/Eigen APIs
need a dedicated C shim and are excluded until that interface is designed.
Run after ``sync_headers.py`` updates the SDK's vendored Basilisk headers.
"""

import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
FILE_HEADER = """// This file is AUTO-GENERATED by tools/gen_rust_utilities.py.
// DO NOT EDIT BY HAND.
//
// Source headers: astroConstants.h, macroDefinitions.h, orbitalMotion.h, and
// rigidBodyKinematics.h vendored in bsk_sdk.
//
"""
WRAPPER_TEMPLATE = """\
#include "Basilisk/architecture/utilities/astroConstants.h"
#include "Basilisk/architecture/utilities/macroDefinitions.h"
#include "Basilisk/architecture/utilities/orbitalMotion.h"
#include "Basilisk/architecture/utilities/rigidBodyKinematics.h"

/* Bindgen ignores some guarded/expression macros.  Re-expose the selected
 * values as typed constants without duplicating their definitions in Rust. */
static const double BSK_RUST_G_UNIVERSIAL = G_UNIVERSIAL;
static const double BSK_RUST_SEC2DAY = SEC2DAY;
static const double BSK_RUST_J2_EARTH = J2_EARTH;
static const double BSK_RUST_J3_EARTH = J3_EARTH;
static const double BSK_RUST_J4_EARTH = J4_EARTH;
static const double BSK_RUST_J5_EARTH = J5_EARTH;
static const double BSK_RUST_J6_EARTH = J6_EARTH;
static const double BSK_RUST_J2_MARS = J2_MARS;
"""


def find_bsk_include() -> Path:
    """Return the installed or source-tree bsk-sdk include root."""
    try:
        import bsk_sdk  # type: ignore[import]

        include_dir = Path(bsk_sdk.include_dir())
        if include_dir.exists():
            return include_dir
    except Exception:
        pass

    include_dir = REPO_ROOT / "src" / "bsk_sdk" / "include"
    if include_dir.exists():
        return include_dir
    raise RuntimeError("Cannot locate bsk-sdk include directory.")


def run_bindgen(wrapper_path: Path, include_root: Path) -> str:
    """Run bindgen over the selected C ABI headers."""
    if not shutil.which("bindgen"):
        sys.exit("ERROR: `bindgen` not found on $PATH; run `cargo install bindgen-cli`.")

    allow_functions = (
        "E2f|E2M|f2E|f2H|H2f|H2N|M2E|N2H|"
        "elem2rv|rv2elem|clMeanOscMap|clElem2eqElem|"
        "hillFrame|hill2rv|rv2hill|"
        "atmosphericDensity|debyeLength|atmosphericDrag|solarRad|"
        "addMRP|subMRP|MRP2C|C2MRP|MRP2EP|EP2MRP|"
        "MRPshadow|MRPswitch|dMRP|dMRP2Omega|ddMRP|ddMRP2dOmega|"
        "BmatMRP|BdotmatMRP|BinvMRP|wrapToPi|tilde|Mi"
    )
    allow_constants = (
        "G_UNIVERSIAL|AU|AU2M|SPEED_LIGHT|SOLAR_FLUX_EARTH|"
        "D2R|R2D|RPM|SEC2DAY|EARTH_GRAV|"
        "MU_(SUN|MERCURY|VENUS|EARTH|MOON|MARS|JUPITER|SATURN|URANUS|NEPTUNE|PLUTO)|"
        "REQ_(SUN|MERCURY|VENUS|EARTH|MOON|MARS|JUPITER|SATURN|URANUS|NEPTUNE|PLUTO)|"
        "RP_(EARTH|MARS)|"
        "NANO2SEC|SEC2NANO|SEC2HOUR"
    )
    command = [
        "bindgen",
        str(wrapper_path),
        "--use-core",
        "--no-prepend-enum-name",
        "--merge-extern-blocks",
        "--with-derive-default",
        "--allowlist-type",
        "ClassicElements|equinoctialElements|CelestialObject_t",
        "--allowlist-function",
        f"^({allow_functions})$",
        "--allowlist-var",
        f"^({allow_constants}|BSK_RUST_.*)$",
        "--opaque-type",
        "BSKLogger",
        "--",
        f"-I{include_root}",
        f"-I{include_root / 'Basilisk'}",
        "-std=c++17",
        "-x",
        "c++",
    ]
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode:
        sys.exit(f"ERROR: bindgen failed:\n{result.stderr}")
    return result.stdout


def main() -> None:
    """Generate ``bsk_utilities/src/raw.rs``."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bsk-include", metavar="DIR")
    parser.add_argument(
        "--out",
        default=REPO_ROOT / "rust" / "bsk_utilities" / "src" / "raw.rs",
        type=Path,
    )
    args = parser.parse_args()

    include_root = (
        Path(args.bsk_include).resolve() if args.bsk_include else find_bsk_include()
    )
    with tempfile.NamedTemporaryFile(suffix=".h", mode="w", delete=False) as file:
        file.write(WRAPPER_TEMPLATE)
        wrapper_path = Path(file.name)
    try:
        bindings = run_bindgen(wrapper_path, include_root)
    finally:
        wrapper_path.unlink(missing_ok=True)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(FILE_HEADER + bindings)
    print(f"Wrote {args.out} ({args.out.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
